<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2_view_detail_popular_items</name>
   <tag></tag>
   <elementGuidId>8d5d3d8d-0bd6-4cab-9b7f-93e9bead3f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='details_16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#details_16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0ee2bc19-694e-42fd-8d5c-471b2465d4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_16</value>
      <webElementGuid>5904d09b-094b-4a06-b0e0-e135d0196ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub viewDetail ng-scope</value>
      <webElementGuid>4d0abc6d-2c5c-4888-8b1f-798b869fb3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>View_details</value>
      <webElementGuid>6dd80d67-ebf8-4a71-9e66-89a2f99828fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>d5af8bce-df00-4d71-b8db-21d428872530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_16&quot;)</value>
      <webElementGuid>fe5c17c0-a9ba-4901-9bf3-05e527a20b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='details_16']</value>
      <webElementGuid>5fbf884d-ce77-4b2f-951a-9f24a0d2e5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div/a/label</value>
      <webElementGuid>db3426ae-27ca-4f43-a8df-47791c9cbd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POPULAR ITEMS'])[2]/following::label[1]</value>
      <webElementGuid>7675e1d4-0262-47b2-a485-c3b2f0da0bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[4]/following::label[1]</value>
      <webElementGuid>43afcd55-01b7-46ba-bcfa-2431da8df1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/preceding::label[1]</value>
      <webElementGuid>27a16a67-7ca7-4c46-b9e4-479abffd69e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/preceding::label[2]</value>
      <webElementGuid>8333f24e-4f21-4978-9b16-e11988bd5b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Details']/parent::*</value>
      <webElementGuid>caf0cb7a-1c7b-4c13-ade9-d4eaaab75cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/label</value>
      <webElementGuid>31856283-a86b-4230-b76c-014e9ac6c7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'details_16' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>e9410e9a-6829-4a36-9551-460f1984a7d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
