<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3_next</name>
   <tag></tag>
   <elementGuidId>0ebd7af1-9c96-4bad-b38f-203fdbfea341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#next_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcf52879-7e21-42dd-866d-7515d531e67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_btn</value>
      <webElementGuid>b29fd957-bd01-440f-9298-545110352e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f0b1de0-ceae-4f93-ba2a-9d66ee867710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>shippingDetails_next()</value>
      <webElementGuid>82354d3b-653e-42da-95cc-916199cc7891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button nextBtn marginTop75 ng-scope</value>
      <webElementGuid>02ec7003-4689-42ba-ad18-67ee68f209c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>1e672555-27cd-40c6-a872-00d1c48be4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEXT</value>
      <webElementGuid>feeee58b-aefe-41dc-ae3b-b508e28a2519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userSection&quot;)/div[1]/div[@class=&quot;mobileBtnHandler&quot;]/button[@id=&quot;next_btn&quot;]</value>
      <webElementGuid>eabfbf1e-65da-4014-b720-43c1d949726d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next_btn']</value>
      <webElementGuid>b34b6f56-5e8a-43ab-a112-5c62dd06babd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userSection']/div/div[3]/button</value>
      <webElementGuid>0bd24538-84ec-41eb-ade8-6c1cf4018f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHIPPING BY:'])[1]/following::button[1]</value>
      <webElementGuid>a110aff3-ecb8-43d9-a2a7-362a673090c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit shipping details'])[1]/following::button[1]</value>
      <webElementGuid>0f4e2a58-4c3f-4277-85b1-92dee1c1aea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recipient details'])[1]/preceding::button[1]</value>
      <webElementGuid>a33502d7-07b6-4375-971e-5fd5848abb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::button[1]</value>
      <webElementGuid>33c53569-960a-4cb6-8730-5568d8885482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEXT']/parent::*</value>
      <webElementGuid>72306dde-b062-4aa8-8c01-10ae7641b6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>924689e9-86b7-45d8-b2d1-3ff55b6faa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'next_btn' and (text() = 'NEXT' or . = 'NEXT')]</value>
      <webElementGuid>2a172b44-072d-47c7-af63-934cb7ed610a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
